
## Benötigtes

- Linux Server running Ubuntu 20.04 LTS or newer
- Domain that points to the public IP of your Linux Server

## 1.  Docker / Docker-Compose installieren

### 1.1. Install Docker
```bash
sudo apt update

sudo apt install apt-transport-https ca-certificates curl gnupg-agent software-properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

sudo apt update

sudo apt-get install docker-ce docker-ce-cli containerd.io
```

### 1.2. Docker Überprüfen
```bash
sudo docker run hello-world
```

### 1.3. Install Docker-Compose

Neueste normale Version runterladen

```bash
sudo curl -L "https://github.com/docker/compose/releases/download/1.25.5/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

sudo chmod +x /usr/local/bin/docker-compose
```

### 1.4. Docker-Compose überprüfen
```bash
sudo docker-compose --version
```

### 1.5. Eventuell Nutzer erstellen
```bash
sudo usermod -aG docker $USER
```

## 2. Nginx Proxy Manager

### 2.1. `docker-compose.yml`file erstellen (https://nginxproxymanager.com/guide/) & user/pw/name ändern

...


version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
  db:
    image: 'jc21/mariadb-aria:latest'
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - ./data/mysql:/var/lib/mysql
```

### 2.2. Nginx Proxy Manager starten

```bash
docker-compose up -d
```

## 3. In web UI einloggen

FQDN/IP/localhost:81 anmelden mit admin@example.com & Passwort changeme

## 4. DNS Eintrag / SSL-Zertifikat

Eintrag erstellen lassen 
SSL-Zertifikat Reiter & Domä#ne angeben


